references:
  commands:
    notify_on_fail: &notify_on_fail
      name: Setup PHP
      command: |
        echo php is great
        if [[ $CIRCLE_BRANCH = "master" ]]; then
          echo "fail!"
        fi
      when: on_fail

version: 2
jobs:
  build:
    docker:
      - image: kimh/picard-trusty:5740

    working_directory: /tmp/code
    steps:
      - checkout
      - run: *notify_on_fail

