version: 2
jobs:
  test:
    docker:
      - image: kimh/picard-trusty:5740

    working_directory: /tmp/code
    steps:
      - checkout
      - run: cat circle.yml
      - run: ls -la
      - run: pwd

workflows:
  version: 2
  commit:
    jobs:
      - test
