defaults: &defaults
  - run: echo hello

- &cmd_install_node
    run: echo hello
version: 2
jobs:
  build:
    docker:
      - image: kimh/picard-trusty:5740

    working_directory: /tmp/code
    steps:
      - checkout
      - run: echo hello
      - *cmd_install_node

