version: 2
jobs:
  build:
    docker:
      - image: kimh/picard-trusty:5740

    working_directory: /tmp/code
    steps:
      - run: apt-get -y remove git
      - checkout
      - run: echo hello
      - run: echo this is pr1
