version: 2
jobs:
  test:
    docker:
      - image: kimh/picard-trusty:5740

    working_directory: /tmp/code
    steps:
      - restore_cache:
          keys:
            - cache-key-v1
      - run: mkdir -p my-cache
      - run: echo "abc" > my-cache/cache.txt
      - save_cache:
          key: cache-key-v1
          paths:
            - my-cache

workflows:
  version: 2
  commit:
    jobs:
      - test
