references:
  commands:
    foo: &setup_php
      name: Setup PHP
      command: |
        echo php is great

version: 2
jobs:
  build:
    docker:
      - image: kimh/picard-trusty:5740

    working_directory: /tmp/code
    steps:
      - checkout
      - run: *setup_php

