version: 2
jobs:
  build:
    docker:
      - image: kimh/picard-trusty:5740

    working_directory: /tmp/code
    steps:
      - run: &bundle_install
          name: bundle installの実行
          command: |
            echo "foo"
      - checkout
      - run: echo hello
      - run: *bundle_install
